
server:
  port: ${vcap.application.port:9098}

eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://192.168.248.1:8761}/eureka/

---
spring:
  profiles: cloud
eureka:
  instance:
    hostname: bookmark
    non-secure-port:  9098
